configuration: Release

before_build:
- nuget restore

after_build:
- nuget pack Dynamic.Image.Handler.nuspec -version %APPVEYOR_BUILD_VERSION%
- appveyor PushArtifact Dynamic.Image.Handler.%APPVEYOR_BUILD_VERSION%.nupkg